### ISSUE TITLE
Bug while importing a new map with the 3d text

### ISSUE THREAD

**Issue by RaphaelCapone** [Pottus/Texture-Studio#94]
Hello, after I imported a new map and grouped all the imported objects then moving them as a group, the 3d text just duplicated and won't dissapear with command /hidetex3d.

**Comment by Crayder** [comment]
Can you show me what you mean in a video or something? I'm not reproducing this issue.

**Comment by RaphaelCapone** [comment]
Done: https://youtu.be/qBJScvCeAik

**Comment by Crayder** [comment]
Hmm... Interesting. This still isn't happening to me. What exactly was your process?

What I did was:
- Create a few objects
- /exportmap
- /newmap
- Create a few more objects
- /gall to group select all objects
- /setgroup to set objects to a different group than 0
- /importmap to import the first objects
- /selectgroup 0 to select only the import objects
- /editgroup and moved objects up
- Saved

Everything worked exactly as it should. The labels didn't duplicate like in your video, they just moved. Are you sure you are using the latest files?

**Comment by Crayder** [comment]
I tried doing /loadmap first (the only thing we did different I suppose), and it's still not happening to me... I'm not sure what the problem could be?

**Comment by RaphaelCapone** [comment]
I have no idea, maybe there are created 3d labels by default(when importing new objects with /importmap) who aren't counted as normal labels and then when we try to "control" them with commands like /hidetext3d have no effects. Or maybe the server creates duplicated 3d labels and it could be a bug from the streamer plugin or from the server itself. If I have any other idea what could it be I'll let you know, maybe I'll try to give a look at the code soon and see if I can spot the problem...and if I'll do this I'll make a pull request.
Also, I think there could be a problem with the large objects that my map contains, maybe it slows the server and would not anymore work as it should.... I don't know

**Comment by Crayder** [comment]
If it was any of those problems I would be experiencing the issue as well, apart from having a lot of objects (which also shouldn't affect this because the limit is set higher).

**Comment by RaphaelCapone** [comment]
I really don't know what could it be then...
I can make a server and join together to test by yourself this if you want

**Comment by Crayder** [comment]
Yeah, that'd be helpful if we're ever available at the same time. Let me know via SA-MP Discord?

**Comment by RaphaelCapone** [comment]
Of course! My name on discord is Orion90#0132 .Also I joined the samp community's server and sent you a friend request.
